export const ActionTypes = {
    ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
    DELETE_PRODUCT : "DELETE_PRODUCT",
    ADD_LIKED_PRODUCT : "ADD_LIKED_PRODUCT",
    DELETE_LIKED_PRODUCT : "DELETE_LIKED_PRODUCT",
    FETCH_PRODUCT_BY_TITLE : 'FETCH_PRODUCT_BY_TITLE',
    FETCH_ALL_PRODUCTS : 'FETCH_ALL_PRODUCTS',
    UPDATE_PRODUCT : 'UPDATE_PRODUCT',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    VERIFY_TOKEN_REQUEST : 'VERIFY_TOKEN_REQUEST',
    UPLOAD_IMAGE_REQUEST : 'UPLOAD_IMAGE_REQUEST',// for update list
    UPLOAD_REQUEST : 'UPLOAD_REQUEST',// upload image for for create list
    FETCH_LPRODUCTS_REQUEST : 'FETCH_LPRODUCTS_REQUEST',
    FETCH_PRODUCTS_REQUEST : 'FETCH_PRODUCTS_REQUEST',
    GET_USER_DATA_REQUEST : 'GET_USER_DATA_REQUEST'
}